### PR TITLE
Add serde build to CI

### PR DESCRIPTION
**Pull request by quietlychris**

### CODE REVIEW

**Comment by quietlychris** [comment]
It currently looks like the `serde` feature build isn't building at the moment, either on my local machine using `rustc 1.80.0-nightly` or via the Github Actions. Starting to look into this, but might be a bit slow.

**Comment by quietlychris** [comment]
It appears at first glance like the issue here is the `serde` dependency having default-features set to `false`; the build works when default features are enabled. What was the reasoning behind disabling them?

```toml
[dependencies]
serde = { version = "1.0", features = ["derive"], default-features = false}
```

**Comment by patrickelectric** [comment]
Hi @quietlychris, thanks for pointing this issue, it should be fixed by https://github.com/bluerobotics/ping-rs/pull/50 since we want serde as an optional feature.

**Comment by quietlychris** [comment]
Happy to help! Hope the overlap between this and PR 50 isn't inconvenient, but pulled in the changes you made there and tried to address @RaulTrombin's comments by adding a few feature-based checks to the CI runner.

**Comment by RaulTrombin** [comment]
> Happy to help! Hope the overlap between this and PR 50 isn't inconvenient, but pulled in the changes you made there and tried to address @RaulTrombin's comments by adding a few feature-based checks to the CI runner. 

Hey @quietlychris, can you rebase It ? And modify to just "cargo build" & "cargo build --no-default-features, should be enough!
Thks for reporting these issue and contribution.

**Comment by quietlychris** [comment]
I think that the most recent commits address this, but honestly not sure that I managed the rebase correctly; my code editor is doing something funky today and I'm having a hard time figuring out if the operation was successful. `git log` does appear to be showing the most recent commits from `master`, though .

**Comment by patrickelectric** [comment]
@quietlychris, to rebase, you should do a `git fetch origin` (if origin is how you call our fork), and after that `git checkout your_brach && git rebase origin/master`.

To merge your commits and learn more about git, I would recommend [checking my blog post](https://patrickelectric.work/blog/2020/how-to-rock-flowing-with-git/).

**Pull request closed without merging**
